### ISSUE TITLE
SSM Terminal - last line below window

### ISSUE THREAD

**Issue by captrob** [jnawk/aws-electron#100] opened 2023-03-09 19:52 UTC
When using the SSM terminal to connect to an instance, if there's enough text onscreen to reach the bottom of the window, the last line is below the bottom of the screen so one cannot see what's being typed.

![image](https://user-images.githubusercontent.com/10659576/224138497-58eae1bf-2f94-4c3a-be96-9a993dcd121d.png)

**Comment by jnawk** [comment] 2024-02-19 09:52
@captrob try the latest version; I was not able to reproduce this (on Linux) with the latest version.

**Comment by captrob** [comment] 2024-02-26 22:47
Hi @jnawk - I just tested and it is still an issue on Windows unfortunately.

![image](https://github.com/jnawk/aws-electron/assets/10659576/63305aef-be98-4714-b74b-e4c7c70579fe)

**Comment by jnawk** [comment] 2024-05-17 03:03
fixed in v4

**Closed by jnawk** 2024-05-17 03:03 UTC
